Expand API support, including some V2 endpoints
pixtron/bybit-api pull request #4
Opened 2020-01-16 17:21 UTC by tiagosiebler

Add support for V2 versions of some APIs:
- place order
- cancel order

Add missing APIs:
- cancel all orders
- replace order
- get symbols

Add support for custom order ID for cancel active order.

2020-01-16 18:13 UTC, pixtron requested changes
Can you change `lib/rest-client.js`according to my comments below, and please add the new/changed methods to `doc/rest-client.md`.

2020-01-16 18:13 UTC, pixtron commented on lib/rest-client.js
> +  async placeActiveOrderV2(params) {
I'd suggest to replace `placeActiveOrder` method with this one. The [the docs](https://github.com/bybit-exchange/bybit-official-api-docs/blob/master/en/rest_api.md#active-order) recommend to use v2 method over v1.

I would then publish a new minor or even major version of the module.

2020-01-16 18:13 UTC, pixtron commented on lib/rest-client.js
> +  async cancelActiveOrderV2(params) {
I'd suggest to replace `cancelActiveOrder` with this one, as the docs recommend to use v2.

2020-01-16 20:14 UTC, tiagosiebler commented
Updated

2020-01-17 21:35 UTC, tiagosiebler commented
@pixtron let me know if you need other changes to this, thanks!

2020-01-18 02:01 UTC, merged

2020-01-18 02:01 UTC, pixtron commented
I will add some more missing api endpoints, which where introduced/documented after the release of this wrapper before releasing a new version.

2020-01-18 02:48 UTC, pixtron commented
@tiagosiebler just published v1.1.0 including your changes.